/**:
  ros__parameters:
    start_enabled: true

person_tracker_node:
  ros__parameters:
    mode: "realsense"

    webcam_color_topic: "/camera/color/image_raw"

    realsense_color_topic: "/camera/camera/color/image_raw"
    realsense_depth_topic: "/camera/camera/aligned_depth_to_color/image_raw"
    camera_info_topic: "/camera/camera/color/camera_info"

    model_path: "/home/chan/capston_h3c_integration/src/patrol_yolo/model/yolov8s.engine"  # 후에 절대경로로 수정
    tracker_cfg: "/home/chan/capston_h3c_integration/src/patrol_yolo/config/bytetrack.yaml" # 후에 절대경로로 수정
    conf_thres: 0.35
    iou_thres: 0.45
    use_gpu: true
    imgsz: 544

    enable_topic: "/person_tracking/enable"

    annotated_topic: "/person_tracking/annotated"
    tracks_topic: "/person_tracking/tracks_json"

    depth_roi_half: 3
    min_depth_m: 0.2
    max_depth_m: 8.0
    depth_scale: 0.001

    sync_slop: 0.08
    queue_size: 5

    worker_sleep_ms: 2
    stale_frame_ms: 300
    log_fps: true
    max_process_fps: 15.0


person_following_node:
  ros__parameters:
    tracks_topic: "/person_tracking/tracks_json"
    enable_topic: "/person_tracking/enable"

    target_topic: "/person_tracking/follow_target"
    state_topic: "/person_tracking/follow_state"

    target_strategy: "largest_bbox"

    frame_center_u: 640

    min_confidence: 0.35
    min_bbox_w: 40
    min_bbox_h: 80

    min_stable_hits: 3
    lost_timeout_sec: 3.0
    id_switch_debounce_sec: 0.8
    max_no_depth_streak: 8
    max_frame_age_sec: 0.3

    state_publish_hz: 10.0